modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="wolfchunk_loader"
version="1.0.0"
displayName="WolfChunk Loader"
description='''
Automatically loads chunks around tamed wolves and cats.
'''

[[dependencies.wolfchunk_loader]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="SERVER"
