modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "wolfchunkloader"
version = "1.0"
displayName = "Wolf Chunk Loader"
description = "Loads chunks around tamed wolves and cats"
