modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="wolfchunkloader"
version="1.0"
displayName="Wolf Chunk Loader"
description="Mod, který způsobí, že ochočený vlk nebo kočka načítají okolní chunky (3x3)."
