modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="wolfchunkloader"
version="2.0.1"
displayName="Wolf Chunk Loader"
description='''Tame a wolf to load chunks around it!'''
clientSide = false
serverSide = true
