modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "wolfchunkloader"
version = "1.0"
displayName = "WolfChunkLoader"
description = "Loads 3x3 chunks around tamed wolves and cats every second"
