modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "wolfchunkloader"
version = "1.0.0"
displayName = "Wolf Chunk Loader"
description = "Loads chunks around tamed wolves and cats."
authors = ["YourName"]

[[dependencies.wolfchunkloader]]
modId = "forge"
mandatory = true
versionRange = "[47.4.0,)"
ordering = "NONE"
side = "SERVER"
