modLoader="javafml"
loaderVersion="[47,)" # Forge 1.20.1+
license="MIT"
[[mods]]
modId="wolfchunk_loader"
version="1.0"
displayName="Wolf Chunk Loader"
description='''
Testovací Forge mod.
'''
